# The URL the site will be built for
base_url = "https://connorskees.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
minify_html = true
generate_feed = true

theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"


[extra]
mode = "dark"
menu = [
    { name = "Home", url = "/", weight = 2 },
]
socials = []